/*
 * masters-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = HatchyverseAPI.Client.OpenAPIDateConverter;

namespace HatchyverseAPI.Model
{
    /// <summary>
    /// GameSave
    /// </summary>
    [DataContract(Name = "GameSave")]
    public partial class GameSave
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GameSave" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GameSave() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GameSave" /> class.
        /// </summary>
        /// <param name="uid">uid (required).</param>
        /// <param name="data">data (required).</param>
        /// <param name="gameId">gameId (required).</param>
        /// <param name="saveName">saveName (required).</param>
        /// <param name="userId">userId (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="updatedAt">updatedAt (required).</param>
        public GameSave(string uid = default(string), Dictionary<string, Object> data = default(Dictionary<string, Object>), string gameId = default(string), string saveName = default(string), string userId = default(string), FirebaseFirestoreTimestamp createdAt = default(FirebaseFirestoreTimestamp), FirebaseFirestoreTimestamp updatedAt = default(FirebaseFirestoreTimestamp))
        {
            // to ensure "uid" is required (not null)
            if (uid == null)
            {
                throw new ArgumentNullException("uid is a required property for GameSave and cannot be null");
            }
            this.Uid = uid;
            // to ensure "data" is required (not null)
            if (data == null)
            {
                throw new ArgumentNullException("data is a required property for GameSave and cannot be null");
            }
            this.Data = data;
            // to ensure "gameId" is required (not null)
            if (gameId == null)
            {
                throw new ArgumentNullException("gameId is a required property for GameSave and cannot be null");
            }
            this.GameId = gameId;
            // to ensure "saveName" is required (not null)
            if (saveName == null)
            {
                throw new ArgumentNullException("saveName is a required property for GameSave and cannot be null");
            }
            this.SaveName = saveName;
            // to ensure "userId" is required (not null)
            if (userId == null)
            {
                throw new ArgumentNullException("userId is a required property for GameSave and cannot be null");
            }
            this.UserId = userId;
            // to ensure "createdAt" is required (not null)
            if (createdAt == null)
            {
                throw new ArgumentNullException("createdAt is a required property for GameSave and cannot be null");
            }
            this.CreatedAt = createdAt;
            // to ensure "updatedAt" is required (not null)
            if (updatedAt == null)
            {
                throw new ArgumentNullException("updatedAt is a required property for GameSave and cannot be null");
            }
            this.UpdatedAt = updatedAt;
        }

        /// <summary>
        /// Gets or Sets Uid
        /// </summary>
        [DataMember(Name = "uid", IsRequired = true, EmitDefaultValue = true)]
        public string Uid { get; set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name = "data", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, Object> Data { get; set; }

        /// <summary>
        /// Gets or Sets GameId
        /// </summary>
        [DataMember(Name = "gameId", IsRequired = true, EmitDefaultValue = true)]
        public string GameId { get; set; }

        /// <summary>
        /// Gets or Sets SaveName
        /// </summary>
        [DataMember(Name = "saveName", IsRequired = true, EmitDefaultValue = true)]
        public string SaveName { get; set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [DataMember(Name = "userId", IsRequired = true, EmitDefaultValue = true)]
        public string UserId { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public FirebaseFirestoreTimestamp CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name = "updatedAt", IsRequired = true, EmitDefaultValue = true)]
        public FirebaseFirestoreTimestamp UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GameSave {\n");
            sb.Append("  Uid: ").Append(Uid).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  GameId: ").Append(GameId).Append("\n");
            sb.Append("  SaveName: ").Append(SaveName).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
