/*
 * masters-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = HatchyverseAPI.Client.OpenAPIDateConverter;

namespace HatchyverseAPI.Model
{
    /// <summary>
    /// UserWalletsInner
    /// </summary>
    [DataContract(Name = "User_wallets_inner")]
    public partial class UserWalletsInner
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserWalletsInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UserWalletsInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UserWalletsInner" /> class.
        /// </summary>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="linked">linked (required).</param>
        /// <param name="nonce">nonce (required).</param>
        /// <param name="address">address (required).</param>
        public UserWalletsInner(double createdAt = default(double), bool linked = default(bool), string nonce = default(string), string address = default(string))
        {
            this.CreatedAt = createdAt;
            this.Linked = linked;
            // to ensure "nonce" is required (not null)
            if (nonce == null)
            {
                throw new ArgumentNullException("nonce is a required property for UserWalletsInner and cannot be null");
            }
            this.Nonce = nonce;
            // to ensure "address" is required (not null)
            if (address == null)
            {
                throw new ArgumentNullException("address is a required property for UserWalletsInner and cannot be null");
            }
            this.Address = address;
        }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public double CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets Linked
        /// </summary>
        [DataMember(Name = "linked", IsRequired = true, EmitDefaultValue = true)]
        public bool Linked { get; set; }

        /// <summary>
        /// Gets or Sets Nonce
        /// </summary>
        [DataMember(Name = "nonce", IsRequired = true, EmitDefaultValue = true)]
        public string Nonce { get; set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [DataMember(Name = "address", IsRequired = true, EmitDefaultValue = true)]
        public string Address { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserWalletsInner {\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Linked: ").Append(Linked).Append("\n");
            sb.Append("  Nonce: ").Append(Nonce).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
