/*
 * hatchyverse-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = HatchyverseAPI.Client.OpenAPIDateConverter;

namespace HatchyverseAPI.Model
{
    /// <summary>
    /// AssetAgreement
    /// </summary>
    [DataContract(Name = "AssetAgreement")]
    public partial class AssetAgreement
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AssetAgreement" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AssetAgreement() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AssetAgreement" /> class.
        /// </summary>
        /// <param name="uid">uid (required).</param>
        /// <param name="date">date (required).</param>
        /// <param name="role">role (required).</param>
        /// <param name="accepted">accepted (required).</param>
        public AssetAgreement(string uid = default(string), string date = default(string), string role = default(string), bool accepted = default(bool))
        {
            // to ensure "uid" is required (not null)
            if (uid == null)
            {
                throw new ArgumentNullException("uid is a required property for AssetAgreement and cannot be null");
            }
            this.Uid = uid;
            // to ensure "date" is required (not null)
            if (date == null)
            {
                throw new ArgumentNullException("date is a required property for AssetAgreement and cannot be null");
            }
            this.Date = date;
            // to ensure "role" is required (not null)
            if (role == null)
            {
                throw new ArgumentNullException("role is a required property for AssetAgreement and cannot be null");
            }
            this.Role = role;
            this.Accepted = accepted;
        }

        /// <summary>
        /// Gets or Sets Uid
        /// </summary>
        [DataMember(Name = "uid", IsRequired = true, EmitDefaultValue = true)]
        public string Uid { get; set; }

        /// <summary>
        /// Gets or Sets Date
        /// </summary>
        [DataMember(Name = "date", IsRequired = true, EmitDefaultValue = true)]
        public string Date { get; set; }

        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        [DataMember(Name = "role", IsRequired = true, EmitDefaultValue = true)]
        public string Role { get; set; }

        /// <summary>
        /// Gets or Sets Accepted
        /// </summary>
        [DataMember(Name = "accepted", IsRequired = true, EmitDefaultValue = true)]
        public bool Accepted { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AssetAgreement {\n");
            sb.Append("  Uid: ").Append(Uid).Append("\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("  Accepted: ").Append(Accepted).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
