/*
 * hatchyverse-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = HatchyverseAPI.Client.OpenAPIDateConverter;

namespace HatchyverseAPI.Model
{
    /// <summary>
    /// EventRewardsInner
    /// </summary>
    [DataContract(Name = "Event_rewards_inner")]
    public partial class EventRewardsInner
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EventRewardsInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EventRewardsInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EventRewardsInner" /> class.
        /// </summary>
        /// <param name="assets">assets (required).</param>
        /// <param name="toRank">toRank (required).</param>
        /// <param name="fromRank">fromRank (required).</param>
        public EventRewardsInner(List<EventRewardsInnerAssetsInner> assets = default(List<EventRewardsInnerAssetsInner>), double toRank = default(double), double fromRank = default(double))
        {
            // to ensure "assets" is required (not null)
            if (assets == null)
            {
                throw new ArgumentNullException("assets is a required property for EventRewardsInner and cannot be null");
            }
            this.Assets = assets;
            this.ToRank = toRank;
            this.FromRank = fromRank;
        }

        /// <summary>
        /// Gets or Sets Assets
        /// </summary>
        [DataMember(Name = "assets", IsRequired = true, EmitDefaultValue = true)]
        public List<EventRewardsInnerAssetsInner> Assets { get; set; }

        /// <summary>
        /// Gets or Sets ToRank
        /// </summary>
        [DataMember(Name = "toRank", IsRequired = true, EmitDefaultValue = true)]
        public double ToRank { get; set; }

        /// <summary>
        /// Gets or Sets FromRank
        /// </summary>
        [DataMember(Name = "fromRank", IsRequired = true, EmitDefaultValue = true)]
        public double FromRank { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EventRewardsInner {\n");
            sb.Append("  Assets: ").Append(Assets).Append("\n");
            sb.Append("  ToRank: ").Append(ToRank).Append("\n");
            sb.Append("  FromRank: ").Append(FromRank).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
