/*
 * hatchyverse-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = HatchyverseAPI.Client.OpenAPIDateConverter;

namespace HatchyverseAPI.Model
{
    /// <summary>
    /// GetMastersLootboxJPSignatureRequest
    /// </summary>
    [DataContract(Name = "GetMastersLootboxJPSignature_request")]
    public partial class GetMastersLootboxJPSignatureRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMastersLootboxJPSignatureRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetMastersLootboxJPSignatureRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMastersLootboxJPSignatureRequest" /> class.
        /// </summary>
        /// <param name="receiver">receiver (required).</param>
        /// <param name="amount">amount (required).</param>
        /// <param name="lootboxId">lootboxId (required).</param>
        public GetMastersLootboxJPSignatureRequest(string receiver = default(string), double amount = default(double), double lootboxId = default(double))
        {
            // to ensure "receiver" is required (not null)
            if (receiver == null)
            {
                throw new ArgumentNullException("receiver is a required property for GetMastersLootboxJPSignatureRequest and cannot be null");
            }
            this.Receiver = receiver;
            this.Amount = amount;
            this.LootboxId = lootboxId;
        }

        /// <summary>
        /// Gets or Sets Receiver
        /// </summary>
        [DataMember(Name = "receiver", IsRequired = true, EmitDefaultValue = true)]
        public string Receiver { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        public double Amount { get; set; }

        /// <summary>
        /// Gets or Sets LootboxId
        /// </summary>
        [DataMember(Name = "lootboxId", IsRequired = true, EmitDefaultValue = true)]
        public double LootboxId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetMastersLootboxJPSignatureRequest {\n");
            sb.Append("  Receiver: ").Append(Receiver).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  LootboxId: ").Append(LootboxId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
