/*
 * hatchyverse-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = HatchyverseAPI.Client.OpenAPIDateConverter;

namespace HatchyverseAPI.Model
{
    /// <summary>
    /// GiveVoucherToUserRequest
    /// </summary>
    [DataContract(Name = "GiveVoucherToUser_request")]
    public partial class GiveVoucherToUserRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GiveVoucherToUserRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GiveVoucherToUserRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GiveVoucherToUserRequest" /> class.
        /// </summary>
        /// <param name="overrideTokenId">overrideTokenId.</param>
        /// <param name="amount">amount (required).</param>
        /// <param name="assetId">assetId (required).</param>
        /// <param name="email">email (required).</param>
        public GiveVoucherToUserRequest(string overrideTokenId = default(string), double amount = default(double), string assetId = default(string), string email = default(string))
        {
            this.Amount = amount;
            // to ensure "assetId" is required (not null)
            if (assetId == null)
            {
                throw new ArgumentNullException("assetId is a required property for GiveVoucherToUserRequest and cannot be null");
            }
            this.AssetId = assetId;
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for GiveVoucherToUserRequest and cannot be null");
            }
            this.Email = email;
            this.OverrideTokenId = overrideTokenId;
        }

        /// <summary>
        /// Gets or Sets OverrideTokenId
        /// </summary>
        [DataMember(Name = "overrideTokenId", EmitDefaultValue = false)]
        public string OverrideTokenId { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        public double Amount { get; set; }

        /// <summary>
        /// Gets or Sets AssetId
        /// </summary>
        [DataMember(Name = "assetId", IsRequired = true, EmitDefaultValue = true)]
        public string AssetId { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GiveVoucherToUserRequest {\n");
            sb.Append("  OverrideTokenId: ").Append(OverrideTokenId).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  AssetId: ").Append(AssetId).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
