/*
 * hatchyverse-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = HatchyverseAPI.Client.OpenAPIDateConverter;

namespace HatchyverseAPI.Model
{
    /// <summary>
    /// HatchyBalance
    /// </summary>
    [DataContract(Name = "HatchyBalance")]
    public partial class HatchyBalance
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HatchyBalance" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HatchyBalance() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="HatchyBalance" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="element">element (required).</param>
        /// <param name="image">image (required).</param>
        /// <param name="commonAmount">commonAmount (required).</param>
        /// <param name="shinyAmount">shinyAmount (required).</param>
        public HatchyBalance(double id = default(double), string name = default(string), string element = default(string), string image = default(string), double commonAmount = default(double), double shinyAmount = default(double))
        {
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for HatchyBalance and cannot be null");
            }
            this.Name = name;
            // to ensure "element" is required (not null)
            if (element == null)
            {
                throw new ArgumentNullException("element is a required property for HatchyBalance and cannot be null");
            }
            this.Element = element;
            // to ensure "image" is required (not null)
            if (image == null)
            {
                throw new ArgumentNullException("image is a required property for HatchyBalance and cannot be null");
            }
            this.Image = image;
            this.CommonAmount = commonAmount;
            this.ShinyAmount = shinyAmount;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public double Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Element
        /// </summary>
        [DataMember(Name = "element", IsRequired = true, EmitDefaultValue = true)]
        public string Element { get; set; }

        /// <summary>
        /// Gets or Sets Image
        /// </summary>
        [DataMember(Name = "image", IsRequired = true, EmitDefaultValue = true)]
        public string Image { get; set; }

        /// <summary>
        /// Gets or Sets CommonAmount
        /// </summary>
        [DataMember(Name = "commonAmount", IsRequired = true, EmitDefaultValue = true)]
        public double CommonAmount { get; set; }

        /// <summary>
        /// Gets or Sets ShinyAmount
        /// </summary>
        [DataMember(Name = "shinyAmount", IsRequired = true, EmitDefaultValue = true)]
        public double ShinyAmount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HatchyBalance {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Element: ").Append(Element).Append("\n");
            sb.Append("  Image: ").Append(Image).Append("\n");
            sb.Append("  CommonAmount: ").Append(CommonAmount).Append("\n");
            sb.Append("  ShinyAmount: ").Append(ShinyAmount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
