/*
 * masters-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = HatchyverseAPI.Client.OpenAPIDateConverter;

namespace HatchyverseAPI.Model
{
    /// <summary>
    /// MastersMintTrait
    /// </summary>
    [DataContract(Name = "MastersMintTrait")]
    public partial class MastersMintTrait
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MastersMintTrait" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MastersMintTrait() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MastersMintTrait" /> class.
        /// </summary>
        /// <param name="colors">colors (required).</param>
        /// <param name="traits">traits (required).</param>
        /// <param name="type">type (required).</param>
        public MastersMintTrait(List<MastersColor> colors = default(List<MastersColor>), List<MastersTrait> traits = default(List<MastersTrait>), MastersTraitType type = default(MastersTraitType))
        {
            // to ensure "colors" is required (not null)
            if (colors == null)
            {
                throw new ArgumentNullException("colors is a required property for MastersMintTrait and cannot be null");
            }
            this.Colors = colors;
            // to ensure "traits" is required (not null)
            if (traits == null)
            {
                throw new ArgumentNullException("traits is a required property for MastersMintTrait and cannot be null");
            }
            this.Traits = traits;
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for MastersMintTrait and cannot be null");
            }
            this.Type = type;
        }

        /// <summary>
        /// Gets or Sets Colors
        /// </summary>
        [DataMember(Name = "colors", IsRequired = true, EmitDefaultValue = true)]
        public List<MastersColor> Colors { get; set; }

        /// <summary>
        /// Gets or Sets Traits
        /// </summary>
        [DataMember(Name = "traits", IsRequired = true, EmitDefaultValue = true)]
        public List<MastersTrait> Traits { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public MastersTraitType Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MastersMintTrait {\n");
            sb.Append("  Colors: ").Append(Colors).Append("\n");
            sb.Append("  Traits: ").Append(Traits).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
