/*
 * hatchyverse-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = HatchyverseAPI.Client.OpenAPIDateConverter;

namespace HatchyverseAPI.Model
{
    /// <summary>
    /// MastersLootboxJoepegsSignatureNonce
    /// </summary>
    [DataContract(Name = "MastersLootboxJoepegsSignature_nonce")]
    public partial class MastersLootboxJoepegsSignatureNonce
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MastersLootboxJoepegsSignatureNonce" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MastersLootboxJoepegsSignatureNonce() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MastersLootboxJoepegsSignatureNonce" /> class.
        /// </summary>
        /// <param name="type">type (required).</param>
        /// <param name="hex">hex (required).</param>
        public MastersLootboxJoepegsSignatureNonce(string type = default(string), string hex = default(string))
        {
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for MastersLootboxJoepegsSignatureNonce and cannot be null");
            }
            this.Type = type;
            // to ensure "hex" is required (not null)
            if (hex == null)
            {
                throw new ArgumentNullException("hex is a required property for MastersLootboxJoepegsSignatureNonce and cannot be null");
            }
            this.Hex = hex;
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Hex
        /// </summary>
        [DataMember(Name = "hex", IsRequired = true, EmitDefaultValue = true)]
        public string Hex { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MastersLootboxJoepegsSignatureNonce {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Hex: ").Append(Hex).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
