/*
 * hatchyverse-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = HatchyverseAPI.Client.OpenAPIDateConverter;

namespace HatchyverseAPI.Model
{
    /// <summary>
    /// MastersLootboxItem
    /// </summary>
    [DataContract(Name = "MastersLootboxItem")]
    public partial class MastersLootboxItem
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MastersLootboxItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MastersLootboxItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MastersLootboxItem" /> class.
        /// </summary>
        /// <param name="weight">weight (required).</param>
        /// <param name="lootbox">lootbox (required).</param>
        /// <param name="item">item (required).</param>
        public MastersLootboxItem(double weight = default(double), double lootbox = default(double), MastersItem item = default(MastersItem))
        {
            this.Weight = weight;
            this.Lootbox = lootbox;
            // to ensure "item" is required (not null)
            if (item == null)
            {
                throw new ArgumentNullException("item is a required property for MastersLootboxItem and cannot be null");
            }
            this.Item = item;
        }

        /// <summary>
        /// Gets or Sets Weight
        /// </summary>
        [DataMember(Name = "weight", IsRequired = true, EmitDefaultValue = true)]
        public double Weight { get; set; }

        /// <summary>
        /// Gets or Sets Lootbox
        /// </summary>
        [DataMember(Name = "lootbox", IsRequired = true, EmitDefaultValue = true)]
        public double Lootbox { get; set; }

        /// <summary>
        /// Gets or Sets Item
        /// </summary>
        [DataMember(Name = "item", IsRequired = true, EmitDefaultValue = true)]
        public MastersItem Item { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MastersLootboxItem {\n");
            sb.Append("  Weight: ").Append(Weight).Append("\n");
            sb.Append("  Lootbox: ").Append(Lootbox).Append("\n");
            sb.Append("  Item: ").Append(Item).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
