/*
 * hatchyverse-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = HatchyverseAPI.Client.OpenAPIDateConverter;

namespace HatchyverseAPI.Model
{
    /// <summary>
    /// From T, pick a set of properties whose keys are in the union K
    /// </summary>
    [DataContract(Name = "Pick_ApiKey.Exclude_keyofApiKey.uid-or-createdAt-or-updatedAt-or-apiKey__")]
    public partial class PickApiKeyExcludeKeyofApiKeyUidOrCreatedAtOrUpdatedAtOrApiKey
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PickApiKeyExcludeKeyofApiKeyUidOrCreatedAtOrUpdatedAtOrApiKey" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PickApiKeyExcludeKeyofApiKeyUidOrCreatedAtOrUpdatedAtOrApiKey() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PickApiKeyExcludeKeyofApiKeyUidOrCreatedAtOrUpdatedAtOrApiKey" /> class.
        /// </summary>
        /// <param name="name">name (required).</param>
        /// <param name="permissions">permissions (required).</param>
        /// <param name="appId">appId.</param>
        /// <param name="balance">balance (required).</param>
        public PickApiKeyExcludeKeyofApiKeyUidOrCreatedAtOrUpdatedAtOrApiKey(string name = default(string), List<string> permissions = default(List<string>), string appId = default(string), Dictionary<string, double> balance = default(Dictionary<string, double>))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for PickApiKeyExcludeKeyofApiKeyUidOrCreatedAtOrUpdatedAtOrApiKey and cannot be null");
            }
            this.Name = name;
            // to ensure "permissions" is required (not null)
            if (permissions == null)
            {
                throw new ArgumentNullException("permissions is a required property for PickApiKeyExcludeKeyofApiKeyUidOrCreatedAtOrUpdatedAtOrApiKey and cannot be null");
            }
            this.Permissions = permissions;
            // to ensure "balance" is required (not null)
            if (balance == null)
            {
                throw new ArgumentNullException("balance is a required property for PickApiKeyExcludeKeyofApiKeyUidOrCreatedAtOrUpdatedAtOrApiKey and cannot be null");
            }
            this.Balance = balance;
            this.AppId = appId;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Permissions
        /// </summary>
        [DataMember(Name = "permissions", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Permissions { get; set; }

        /// <summary>
        /// Gets or Sets AppId
        /// </summary>
        [DataMember(Name = "appId", EmitDefaultValue = false)]
        public string AppId { get; set; }

        /// <summary>
        /// Gets or Sets Balance
        /// </summary>
        [DataMember(Name = "balance", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, double> Balance { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PickApiKeyExcludeKeyofApiKeyUidOrCreatedAtOrUpdatedAtOrApiKey {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Permissions: ").Append(Permissions).Append("\n");
            sb.Append("  AppId: ").Append(AppId).Append("\n");
            sb.Append("  Balance: ").Append(Balance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
