/*
 * hatchyverse-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = HatchyverseAPI.Client.OpenAPIDateConverter;

namespace HatchyverseAPI.Model
{
    /// <summary>
    /// SyncDepositedAssetsRequest
    /// </summary>
    [DataContract(Name = "SyncDepositedAssets_request")]
    public partial class SyncDepositedAssetsRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SyncDepositedAssetsRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SyncDepositedAssetsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SyncDepositedAssetsRequest" /> class.
        /// </summary>
        /// <param name="depositId">depositId (required).</param>
        /// <param name="receiver">receiver (required).</param>
        public SyncDepositedAssetsRequest(double depositId = default(double), string receiver = default(string))
        {
            this.DepositId = depositId;
            // to ensure "receiver" is required (not null)
            if (receiver == null)
            {
                throw new ArgumentNullException("receiver is a required property for SyncDepositedAssetsRequest and cannot be null");
            }
            this.Receiver = receiver;
        }

        /// <summary>
        /// Gets or Sets DepositId
        /// </summary>
        [DataMember(Name = "depositId", IsRequired = true, EmitDefaultValue = true)]
        public double DepositId { get; set; }

        /// <summary>
        /// Gets or Sets Receiver
        /// </summary>
        [DataMember(Name = "receiver", IsRequired = true, EmitDefaultValue = true)]
        public string Receiver { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SyncDepositedAssetsRequest {\n");
            sb.Append("  DepositId: ").Append(DepositId).Append("\n");
            sb.Append("  Receiver: ").Append(Receiver).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
